### ISSUE TITLE
calculation of standard score is wrong from the proffessor

### ISSUE THREAD

**Issue by JonathanBrunssen** [Korasi/COSC-1336#5]
you get the standard score from (testscore - mean)/standard deviation. the way how he the proffesor has it is (mean - testscore)/standard deviation proof https://statistics.laerd.com/statistical-guides/standard-score-2.php

**Comment by Korasi** [comment]
I didn't check how the professor did the formulas. I already had the proper formulas in place.

```python
dev = mean - score #calculate deviation from the mean
sd1 = dev / std #calculate the standard score
```
